### ISSUE TITLE
Wither Effect Does Not Work.

### ISSUE THREAD

**Issue by kiwiandoesthings** [ItsmagmaMan09/The-Corruption#1]
The wither effect you get when standing on the corruption block does not deal any damage to the player or other entities. I think it is because the effect is for 0 seconds, and it takes a bit for the damage to kick in from the wither effect.

**Comment by ItsmagmaMan09** [comment]
I have noticed this issue after later testing after the initial release, but I have started to work on this in the next update, it will probably release next week!

**Comment by ItsmagmaMan09** [comment]
This issue has now been resolved in the latest release, which can be downloaded [here](https://github.com/ItsmagmaMan09/The-Corruption/releases)! Enjoy, I will now also close this issue!
